<?php 
    $groups = Mage::helper('squeezol_payment')->getGroupsData(); 

    $customerId = Mage::getSingleton('customer/session')->getCustomer()->getId();

    $sql    = 'SELECT * FROM squeezol_groups WHERE group_id IS NULL AND user_id = ' . $customerId;
    $orders = Mage::getSingleton('core/resource') ->getConnection('core_read')->fetchAll($sql);
?>

<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/images/squeezol_payment/fenicottero.png" style="height: 100px;float: left;" />
<h2 style="float: left;margin-left: 20px; margin-top: 62px;">Collette attive</h2>

<table class="sq-table sq-table-bordered">
    <tr>
        <th>Nome colletta</th>
        <th>Immagine</th>
        <th>Giorni mancanti</th>
        <th>Totale da pagare</th>
        <th>Totale pagato</th>
        <th></th>
    </tr>

    <?php foreach ($groups as $g): ?>
    <tr>
        <td><?php echo $g['name']; ?></td>
        <td><img style="width: 80px;" src="<?php echo $g['picture']; ?>" /></td>
        <td><?php echo $g['days_left']; ?></td>
        <td><?php echo money_format('%.2n', $g['amount']) . ' ' . $g['currency']; ?></td>
        <td><?php echo money_format('%.2n', $g['total_paid']) . ' ' . $g['currency']; ?></td>
        <td><a href="<?php echo Mage::getBaseUrl(); ?>squeezol/index/digest/?page=<?php echo $g['id']; ?>">Vai alla colletta</a></td>
    </tr>
    <?php endforeach; ?>
</table>

<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/base/default/images/squeezol_payment/fenicottero.png" style="height: 100px;float: left;" />
<h2 style="float: left;margin-left: 20px; margin-top: 62px;">Ordini da completare</h2>

<table class="sq-table sq-table-bordered">
    <tr>
        <th>Ordine</th>
        <th>Visualizza</th>
        <th>Crea colletta</th>
    </tr>

    <?php foreach ($orders as $o): ?>
<?php $ord = Mage::getModel('sales/order')->loadByIncrementId($o['order_id'])->getId(); ?>
    <tr>
        <td>#<?php echo $o['order_id']; ?></td>
        <td><a href="<?php echo Mage::getBaseUrl(); ?>sales/order/view/order_id/<?php echo $ord; ?>/">Visualizza</a></td>
        <td><a href="<?php echo Mage::getBaseUrl(); ?>squeezol/index/gateway/?oid=<?php echo $o['order_id']; ?>">Crea</a></td>
    </tr>
    <?php endforeach; ?>
</table>
