<script>
var img_url = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>/frontend/base/default/images/squeezol_payment/';
</script>

<h3>Paga con Squeezol</h3>

<h4>
Stai per pagare i seguenti oggetti con Squeezol: ti permetterà di dividire il costo
del carrello con amici, famigliari, parenti.
</h4>
<p>Non aver fretta, i partecipanti avranno 25 giorni di tempo per completare l'acquisto</p>
<table class="shipping-data sq-table sq-table-bordered">
    <tr>
        <th>Oggetto</th>
        <th>Quantit&agrave;</th>
        <th>Prezzo</th>
    </tr>

    <?php foreach ($this->getOrderItems() as $item): ?>
    <?php
        $data  = $item->getData(); 
    ?>

        <tr>
            <td><?php echo $data['name']; ?></td>
            <td><?php echo round($data['qty_ordered']); ?></td>
            <td><?php echo money_format('%.2n', $data['price_incl_tax']); ?></td>
        </tr>
    <?php endforeach; ?>

    <?php $order = $this->getOrderData(); ?>
    <tr>
        <td></td>
        <td class="bld">Spedizione</td>
        <td><?php echo money_format('%.2n', $order['base_shipping_amount']); ?></td>
    </tr>
    <tr>
        <td></td>
        <td class="bld">Totale</td>
        <td><?php echo money_format('%.2n', $order['base_grand_total']); ?></td>
    </tr>
</table>

<div id="squeezol_btn"></div>

<script> SqueezolApi.createSqButton('<?php echo Mage::getBaseUrl(); ?>/squeezol/index/oauth', 'big'); </script>
