<script>
var img_url = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>/frontend/base/default/images/squeezol_payment/';
</script>

<h3>Paga con Squeezol</h3>

<h4 class="sq-text">
Squeezol ti permette di dividire il costo del carrello con amici, colleghi e parenti.
</h4>

<h3> Come procedere: </h3>
  <p> <p class="sq-text">Clicca su Pay With Squeezol</p> e autorizza l'utilizzo del servizio. </p>
  <p> Dai un nome e una descrizione alla colletta e dillo ai tuoi invitati con email e Facebook.</p>
  <p> <p class="sq-text">Paga la tua quota</p> e...non aver fretta, i partecipanti avranno <p class="sq-text">20 giorni</p> di tempo per completare l'acquisto!</p>

<div id="squeezol_btn"></div>

<table class="shipping-data sq-table sq-table-bordered">
    <tr>
        <th>Oggetto</th>
        <th>Quantit&agrave;</th>
        <th>Prezzo</th>
    </tr>

    <?php foreach ($this->getOrderItems() as $item): ?>
    <?php
        $data  = $item->getData(); 
    ?>

        <tr>
            <td><?php echo $data['name']; ?></td>
            <td><?php echo round($data['qty_ordered']); ?></td>
            <td><?php echo money_format('%.2n', $data['price_incl_tax']); ?></td>
        </tr>
    <?php endforeach; ?>

    <?php $order = $this->getOrderData(); ?>
    <tr>
        <td></td>
        <td class="bld">Spedizione</td>
        <td><?php echo money_format('%.2n', $order['base_shipping_amount']); ?></td>
    </tr>
    <tr>
        <td></td>
        <td class="bld">Totale</td>
        <td><?php echo money_format('%.2n', $order['base_grand_total']); ?></td>
    </tr>
</table>

<script> SqueezolApi.createSqButton('<?php echo Mage::getBaseUrl(); ?>/squeezol/index/oauth', 'big'); </script>
